import 'package:hive_flutter/hive_flutter.dart';
import '../models/note.dart';
import '../models/reminder.dart';
import '../models/chat_history.dart';
import '../models/faq.dart';

class DatabaseService {
  static bool _isInitialized = false;
  
  // Box names
  static const String _notesBox = 'notes';
  static const String _remindersBox = 'reminders';
  static const String _chatHistoryBox = 'chat_history';
  static const String _faqBox = 'faq';

  Future<void> initialize() async {
    if (_isInitialized) return;

    await Hive.initFlutter();
    
    // Register adapters (these will be generated by build_runner)
    Hive.registerAdapter(NoteAdapter());
    Hive.registerAdapter(ReminderAdapter());
    Hive.registerAdapter(ChatHistoryAdapter());
    Hive.registerAdapter(FAQAdapter());

    // Open boxes
    await Hive.openBox<Note>(_notesBox);
    await Hive.openBox<Reminder>(_remindersBox);
    await Hive.openBox<ChatHistory>(_chatHistoryBox);
    await Hive.openBox<FAQ>(_faqBox);

    // Initialize default FAQs
    await _initializeDefaultFAQs();

    _isInitialized = true;
  }

  // Note operations
  Future<void> saveNote(Note note) async {
    final box = Hive.box<Note>(_notesBox);
    await box.put(note.id, note);
  }

  Future<List<Note>> getAllNotes() async {
    final box = Hive.box<Note>(_notesBox);
    return box.values.toList()..sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
  }

  Future<Note?> getNote(String id) async {
    final box = Hive.box<Note>(_notesBox);
    return box.get(id);
  }

  Future<void> deleteNote(String id) async {
    final box = Hive.box<Note>(_notesBox);
    await box.delete(id);
  }

  Future<List<Note>> searchNotes(String query) async {
    final box = Hive.box<Note>(_notesBox);
    final allNotes = box.values.toList();
    final lowerQuery = query.toLowerCase();
    
    return allNotes.where((note) =>
        note.title.toLowerCase().contains(lowerQuery) ||
        note.content.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  // Reminder operations
  Future<void> saveReminder(Reminder reminder) async {
    final box = Hive.box<Reminder>(_remindersBox);
    await box.put(reminder.id, reminder);
  }

  Future<List<Reminder>> getAllReminders() async {
    final box = Hive.box<Reminder>(_remindersBox);
    return box.values.toList()..sort((a, b) => a.scheduledTime.compareTo(b.scheduledTime));
  }

  Future<Reminder?> getReminder(String id) async {
    final box = Hive.box<Reminder>(_remindersBox);
    return box.get(id);
  }

  Future<void> deleteReminder(String id) async {
    final box = Hive.box<Reminder>(_remindersBox);
    await box.delete(id);
  }

  Future<void> deleteAllReminders() async {
    final box = Hive.box<Reminder>(_remindersBox);
    await box.clear();
  }

  Future<void> completeReminder(String id) async {
    final box = Hive.box<Reminder>(_remindersBox);
    final reminder = box.get(id);
    if (reminder != null) {
      final updatedReminder = reminder.copyWith(isCompleted: true);
      await box.put(id, updatedReminder);
    }
  }

  // Chat History operations
  Future<void> saveChatHistory(ChatHistory chatHistory) async {
    final box = Hive.box<ChatHistory>(_chatHistoryBox);
    await box.put(chatHistory.id, chatHistory);
  }

  Future<List<ChatHistory>> getAllChatHistory() async {
    final box = Hive.box<ChatHistory>(_chatHistoryBox);
    return box.values.toList()..sort((a, b) => b.timestamp.compareTo(a.timestamp));
  }

  Future<List<ChatHistory>> getRecentChatHistory({int limit = 50}) async {
    final allHistory = await getAllChatHistory();
    return allHistory.take(limit).toList();
  }

  Future<void> deleteChatHistory(String id) async {
    final box = Hive.box<ChatHistory>(_chatHistoryBox);
    await box.delete(id);
  }

  Future<void> clearAllChatHistory() async {
    final box = Hive.box<ChatHistory>(_chatHistoryBox);
    await box.clear();
  }

  Future<List<ChatHistory>> searchChatHistory(String query) async {
    final box = Hive.box<ChatHistory>(_chatHistoryBox);
    final allHistory = box.values.toList();
    final lowerQuery = query.toLowerCase();
    
    return allHistory.where((chat) =>
        chat.userMessage.toLowerCase().contains(lowerQuery) ||
        chat.assistantResponse.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  // FAQ operations
  Future<void> saveFAQ(FAQ faq) async {
    final box = Hive.box<FAQ>(_faqBox);
    await box.put(faq.id, faq);
  }

  Future<List<FAQ>> getAllFAQs() async {
    final box = Hive.box<FAQ>(_faqBox);
    return box.values.toList();
  }

  Future<FAQ?> getFAQ(String id) async {
    final box = Hive.box<FAQ>(_faqBox);
    return box.get(id);
  }

  Future<List<FAQ>> searchFAQs(String query) async {
    final box = Hive.box<FAQ>(_faqBox);
    final allFAQs = box.values.toList();
    final lowerQuery = query.toLowerCase();
    
    return allFAQs.where((faq) =>
        faq.question.toLowerCase().contains(lowerQuery) ||
        faq.answer.toLowerCase().contains(lowerQuery) ||
        faq.keywords.any((keyword) => keyword.toLowerCase().contains(lowerQuery))
    ).toList();
  }

  Future<String?> findFAQAnswer(String question) async {
    final faqs = await searchFAQs(question);
    if (faqs.isNotEmpty) {
      return faqs.first.answer;
    }
    return null;
  }

  // Initialize default FAQs
  Future<void> _initializeDefaultFAQs() async {
    final box = Hive.box<FAQ>(_faqBox);
    
    // Only initialize if the box is empty
    if (box.isEmpty) {
      final defaultFAQs = [
        FAQ(
          id: '1',
          question: 'What can you do?',
          answer: 'I can help you with voice commands, set reminders, tell jokes, provide weather updates, take notes, and answer questions using AI.',
          keywords: ['capabilities', 'features', 'help', 'what', 'can', 'do'],
          category: 'general',
        ),
        FAQ(
          id: '2',
          question: 'How do I set a reminder?',
          answer: 'Just say "remind me to [task]" or "set a reminder for [task]". You can also specify a time like "remind me in 30 minutes".',
          keywords: ['reminder', 'set', 'schedule', 'alarm'],
          category: 'reminders',
        ),
        FAQ(
          id: '3',
          question: 'How do I take notes?',
          answer: 'Say "take a note" or "create a note" followed by what you want to record. You can also say "note that [content]".',
          keywords: ['notes', 'write', 'record', 'save'],
          category: 'notes',
        ),
        FAQ(
          id: '4',
          question: 'Can you tell jokes?',
          answer: 'Yes! Just ask me to "tell a joke" or "make me laugh". I can also tell riddles if you ask for one.',
          keywords: ['jokes', 'funny', 'humor', 'laugh', 'riddle'],
          category: 'entertainment',
        ),
        FAQ(
          id: '5',
          question: 'How do I check the weather?',
          answer: 'Ask me "what\'s the weather?" or "how\'s the weather today?" and I\'ll give you current conditions.',
          keywords: ['weather', 'temperature', 'forecast', 'climate'],
          category: 'weather',
        ),
        FAQ(
          id: '6',
          question: 'How do I change settings?',
          answer: 'Say "open settings" or "go to settings" to access app preferences, theme options, and accessibility features.',
          keywords: ['settings', 'preferences', 'options', 'configure'],
          category: 'settings',
        ),
        FAQ(
          id: '7',
          question: 'Is my data safe?',
          answer: 'Yes, all your data is stored locally on your device. Notes, reminders, and chat history are not shared with external services.',
          keywords: ['privacy', 'security', 'data', 'safe', 'local'],
          category: 'privacy',
        ),
        FAQ(
          id: '8',
          question: 'Can you work offline?',
          answer: 'Some features work offline like jokes, quotes, notes, and reminders. AI responses and weather require an internet connection.',
          keywords: ['offline', 'internet', 'connection', 'network'],
          category: 'connectivity',
        ),
      ];

      for (final faq in defaultFAQs) {
        await box.put(faq.id, faq);
      }
    }
  }

  // Database statistics
  Future<Map<String, int>> getDatabaseStats() async {
    final notesBox = Hive.box<Note>(_notesBox);
    final remindersBox = Hive.box<Reminder>(_remindersBox);
    final chatBox = Hive.box<ChatHistory>(_chatHistoryBox);
    final faqBox = Hive.box<FAQ>(_faqBox);

    return {
      'notes': notesBox.length,
      'reminders': remindersBox.length,
      'chatHistory': chatBox.length,
      'faqs': faqBox.length,
    };
  }

  // Close all boxes (call this when app is closing)
  Future<void> dispose() async {
    await Hive.close();
  }
}
